language: cpp

install:
  - pip install --user -q conan
  - conan user

script:
  - mkdir build && cd build
  - conan install .. --build -s compiler.libcxx=libstdc++11
  - cmake ..
  - cmake --build .
  - ./bin/test_hello
